### ISSUE TITLE
Request with pathParam returning 400 code

### ISSUE THREAD

**Issue by Ukrainis** [usebruno/bruno#2439]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When using :pathParam in request, then getting response code 400. Same with hardcoded parameter giving correct response.
In attachment you will find two same requests, one with pathParam (returns 400), second without (returns 200 and correct data). And two screenshots of same requests.

### .bru file to reproduce the bug

Not working:
meta {
  name: Get user with pathParam
  type: http
  seq: 2
}

get {
  url: https://spring-boot-test-aplication.herokuapp.com/api/users/findById/:id
  body: none
  auth: none
}

params:path {
  id: 16
}
Same but without pathParam and working:
meta {
  name: Get user without pathParam
  type: http
  seq: 3
}

get {
  url: https://spring-boot-test-aplication.herokuapp.com/api/users/findById/16
  body: none
  auth: none
}

### Screenshots/Live demo link

![Using_pathParam](https://github.com/usebruno/bruno/assets/11504404/2141e62e-9d4b-4957-89ca-71686330166f)
![Without_pathParam](https://github.com/usebruno/bruno/assets/11504404/88169902-8b46-4bb8-8950-d5cb26f53d59)

**Comment by fgrande** [comment]
On my Mac, Bruno 1.19.0 works fine, with a path param at the end of a call.
Not able to reproduce what @Ukrainis says, in both cases (with/without param) the application returns 404 (due to application not found)

**Comment by layereight** [comment]
> We have this issue as well, it seems to only occur when the pathParam is the last element of the url.

Same here. We're always getting HTTP 400 as response.

**Comment by Ukrainis** [comment]
> On my Mac, Bruno 1.19.0 works fine, with a path param at the end of a url. Not able to reproduce what @Ukrainis says, in both cases (with/without param) the application returns 404 (due to application not found)

This is working endpoint, just checked, gave same results, as described in a bug.

> We have this issue as well, it seems to only occur when the pathParam is the last element of the url.

Getting same, when this is not at end of the url.

**Comment by sanjai0py** [comment]
Could you share more information by sending a .bru file or a JSON export? That would be really helpful for investigating the issue further.

**Comment by Ukrainis** [comment]
Attached collection:
[Personal.json](https://github.com/user-attachments/files/15804208/Personal.json)

**Comment by fgrande** [comment]
@sanjai0py I made some test locally, and my fix would work.

**Comment by helloanoop** [comment]
PR has been merged.
Thanks for working on this @fgrande @sanjai0py !

This is set to be released in the upcoming `v1.20.0` release.

**Comment by dave-stone-bah** [comment]
> PR has been merged. Thanks for working on this @fgrande @sanjai0py !
> 
> This is set to be released in the upcoming `v1.20.0` release.

@helloanoop Any info on when that release might happen? Thanks!

**Comment by dave-stone-bah** [comment]
@helloanoop Hi, Anoop!

I have attempted to execute endpoints via the Bruno UI and CLI that contain path parameters. The UI works now (thanks!), but the CLI is still returning 500 errors, and doesn't look like the values for the path parameters in the environment specified on the command line is replacing the path parameters before executing. Does the CLI have a separate bug for path params, or should those have been resolved with these fixes?

**Comment by layereight** [comment]
Hey @dave-stone-bah, @helloanoop,

unfortunately, I can confirm that the bug in Bruno's CLI (version 1.20.0) still remains. 

Just tested a collection using a path parameter as last element of the url in Bruno's UI, which works perfectly. Testing the same collection in Bruno's CLI still fails with HTTP 400 as response.

**Comment by layereight** [comment]
Hey @dave-stone-bah, @helloanoop,

just tested latest Bruno's CLI version 1.20.1. The bug is still there.

Tested a collection using a path parameter as last element of the url in Bruno's UI, which works perfectly. Testing the same collection in Bruno's CLI still fails with HTTP 400 as response.

**Comment by jason-burt-bah** [comment]
CLI issue appears to be resolved in `1.20.3`, for those keeping track.

https://github.com/usebruno/bruno/pull/2465

**Comment by layereight** [comment]
I can confirm, the bug is fixed also in the CLI now. Thanks a lot!
