### ISSUE TITLE
Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'formSerializer')

### ISSUE THREAD

**Issue by sophieshc** [usebruno/bruno#3137]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

With the latest version of Bruno (1.29.0) existing Bruno collection failed while running the first request to fetch the token. Even though for 1.22.0 and 1.26.2 versions everything was running.

### Screenshots/Live demo link

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/d3d918fb-94a3-4542-a297-f0eae5400628">

**Comment by sophieshc** [comment]
instead it should be like this
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/3f12322f-fc98-4f1d-ad7a-ae18c196dda6">

**Comment by NjbBzz** [comment]
Hello, Same for me since I updated to 1.29.0

**Comment by Reece-Carruthers** [comment]
Yeah, few of these issues now for different methods. Hoping a fix is passed soon. Temporary solution is to downgrade to previous version.

#3139, #3135, #3129

**Comment by helloanoop** [comment]
We just released a patch fix `v1.29.1` that should have fixed this issue. Can you please test.

**Comment by NjbBzz** [comment]
Actually, it works if (client_credential) token is requested in collection pre-request script (as described here : https://github.com/usebruno/bruno/discussions/385#discussioncomment-7813010).

Yet, using the collection auth tab, it still fails with same error message

**Comment by NjbBzz** [comment]
OK, I've updated to 1.29.1 and getting token is now OK from both collection auth tab and collection pre-request script.

Yet, in another request where I use env variables in body, those variables are not replaced by their actual value : still some work to do :)

**Comment by NjbBzz** [comment]
Finally OK.
I had to reconsider all the management of the Content-type between header tabs in requests and scripts at both collection and request level.
It seems that precedence rules have changed

**Comment by sreelakshmi-bruno** [comment]
Closing this as this issue has been resolved!
