### ISSUE TITLE
Expect not defined inside script sections

### ISSUE THREAD

**Issue by ElSeniorMikael** [usebruno/bruno#3205]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Me and my team have made a collection with bruno, he made some custom script in the collections "Post-response-script" with some expect testings before settings up some key, so the problem is , the script work on his side but on my side Bruno is giving me an error because he cannot use expect. (see the screenshot).

If i comment the testing part "expect", the request pass but whenever there's an expect inside "script" section bruno cannot exec the request

### Screenshots/Live demo link

![Screenshot 2024-09-26 at 10 47 57 AM](https://github.com/user-attachments/assets/0e0f060b-1965-4616-b75f-11e909a65857)

**Comment by ClementValot** [comment]
`expect` comes from the library `chai`, which is loaded by default in the Tests snippets, but not in the Script. 

Still, it is available to be loaded, so adding `const { expect } = require('chai')` at the top of your script should fix it :) 

Did you find a place in the Bruno docs where a similar snippet would be incorrect?

**Comment by ElSeniorMikael** [comment]
@ClementValot 

![Screenshot 2024-09-26 at 1 05 39 PM](https://github.com/user-attachments/assets/c23f8f8e-7f56-423c-a54c-24419542406e)
Even by declaring expect at the top of the script box it still giving me an error

**Comment by Ebeldev** [comment]
Yes me too i'm having issues with expect in the (post or pre) script section.

**Comment by ElSeniorMikael** [comment]
@lohxt1 Like i said in a previous comment, Even by declaring expect at the top of the script box it still giving me an error.

Just for the purpose of showing you, i tried your version and i still get the same error "Error invoking remote method 'send-http-request': VMError: Cannot find module 'chai'"

<img width="1313" alt="Screenshot 2024-10-01 at 8 59 10 AM" src="https://github.com/user-attachments/assets/070d0663-4c8a-4e71-b84d-4b702334b15c">

**Comment by Ebeldev** [comment]
Hi @lohxt1,

I have the version 1.28.0

![Screenshot 2024-10-01 at 8 59 43 AM](https://github.com/user-attachments/assets/5d235962-668f-4460-9cd0-84ed1f570b3d)

What weird, is that it did work expect for a certain time. And then stoped working. 

Does being in developer mode makes it break?

**Comment by sreelakshmi-bruno** [comment]
Hi, can you check if this issue persists in 1.38.1? I'm not able to reproduce this on 1.38.1. Thanks!

**Comment by antis0da** [comment]
@sreelakshmi-bruno I have been experiencing the same behavior using the lodash library within scripts. Even now, with v1.38.1, I can only make it work in "Developer Mode". In "Safe Mode" requests still error out with: "_Error invoking remote method 'send-http-request': Error: Error: Cannot find module lodash_"

**Comment by ElSeniorMikael** [comment]
> Hi, can you check if this issue persists in 1.38.1? I'm not able to reproduce this on 1.38.1. Thanks!

I can confirm that it is still present. We pulled our bruno last week on friday i think and we forgot about the safe/dev mode and couldn't figure out why untill we saw the "safe mode" and remember we need to use it as dev mode.

**Comment by Ebeldev** [comment]
Any update? 

I'm on version 2.4.0 and still have the same problem. 

<img width="651" alt="Image" src="https://github.com/user-attachments/assets/fbb6c8fc-6a3a-433d-95ed-415b4298c661" />

**Comment by anusree-bruno** [comment]
This PR adds support for chai in scripts https://github.com/usebruno/bruno/pull/4552 and also logs these tests

![Image](https://github.com/user-attachments/assets/a89d280b-de6d-4c5c-8463-ea7fbeeb8b20)

**Comment by Ebeldev** [comment]
@anusree-bruno 
Thanks for the pr, i'll wait for the release to update Bruno and fix the problem !

**Comment by anusree-bruno** [comment]
This feature is available in our latest version v2.5.0

**Comment by antis0da** [comment]
@anusree-bruno,  what do you mean by "this feature is available"? I'm running v2.6 and I can confirm that inbuilt libraries like lodash throw a Pre-Request Script Error (Error: cannot find module lodash) when run in "Safe Mode".

**Comment by anusree-bruno** [comment]
Hi @antis0da,
I was referring to the feature that allows writing tests in pre and post scripts.

Regarding Lodash and some other inbuilt libraries — they aren’t available in safe mode due to limitations with our VM. If you need to use these libraries, you can switch to developer mode.

Please refer to our [documentation](https://docs.usebruno.com/testing/script/inbuilt-libraries) to see which libraries are supported in each mode.
