### ISSUE TITLE
Connection refused does not fail test

### ISSUE THREAD

**Issue by koliyo** [usebruno/bruno#3353]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When my service is not running at all, and bruno get connection refused errors, this does not fail test results.

The tests and assertions are not executed, but requests should not be reported as passed, and everything should not be green

### Screenshots/Live demo link

```
[18:40:07] ❯ bru run --env localhost e2e-test/
(node:99034) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Running Folder 

e2e-test/01_post-topic ()
e2e-test/02_post-topic-viewpoint ()
e2e-test/03_post-comment-viewpoint ()
e2e-test/04_post-comment ()

Requests:    4 passed, 4 total
Tests:       0 passed, 0 total
Assertions:  0 passed, 0 total
Ran all requests - 0 ms
```

**Comment by koliyo** [comment]
1.34 is tagged here, but npm cli package is still 1.33, which is the version I'm using

**Comment by helloanoop** [comment]
Thanks for raising this, @koliyo!

I agree that requests shouldn’t be marked as passed, and the entire status shouldn't show green.
@Pragadesh-45, let’s set aside some time next week to review this and get it resolved.

**Comment by WilliamButton** [comment]
This also applies in the UI.  If I am editing tests it is easy to miss the grey Error label and to assume everything is OK because the tests are still green - in fact they haven't been (re)run.

**Comment by Pragadesh-45** [comment]
Hey @WilliamButton,

As I was going through this, I found two things related to it:

1. If the URL is invalid, we are not showing the failure information in the CLI, which was fixed in PR #3451. However, we still need to update the failed requests count in the GUI as well. We are working on improving the GUI in general for the runner.

2. The main issue here is that since the request is sent in the first place, it doesn't call the tests, and therefore the tests are neither passed nor failed. We plan to implement a count for skipped tests to display the relevant information.

**Comment by WilliamButton** [comment]
Thanks @Pragadesh-45.
My scenario in the GUI is similar.  It sounds like this will get fixed with the changes you are describing however, here is some further information.

If I am editing test code I might introduce fatal errors but after sending the request I am still seeing a list of passing tests on the test tab.  I also see a brief 'loading' timer and a 'Cancel request' button which implies incorrectly that the request is being sent.   A related UI problem is the fact that my tests have long titles which expand the panel enough to push the status indicator (and the icons for saving/clearing the response) off of the screen.  This means that there is nothing to indicate a problem until I switch to another tab such as the Response tab where I see an error such as "Error invoking remote method 'send-http-request': ReferenceError: xxxx is not defined".  I hope that helps.

**Comment by AdamJWise** [comment]
It would be ideal if the test code could still run when a connection is refused. A test could report a failure to connect and print helpful text, such as the need to start a proxy before running the test.

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue has been fixed and released. Closing this issue since it's resolved. Please feel free to reopen if you find otherwise. Thanks!
