### ISSUE TITLE
[Feature] Allow configuring headers/authorization for GraphQL schema introspection query

### ISSUE THREAD

**Issue by grubersjoe** [usebruno/bruno#354]
Hey. First of all, great app, thanks for sharing!

My issue is that the GraphQL schema introspection is failing, because it requires authentication with a bearer token and currently there seems no way to provide the credentials:

https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/prepare-gql-introspection-request.js

I'm fetching the token in another request and store it in a collection variable then like this:

```
script:post-response {
  bru.setVar('accessToken', res.body.access_token)
}
```

So ideally there would be some setting where you can configure authorization and/or the headers for the introspection query including support for variables. If you like I can also give this a try and open up a PR :).

**Comment by grubersjoe** [comment]
I'm currently working on it and I think it goes well. I'll open up a PR when I'm ready. There are also surely things that needs to be discussed like the data structure or how the UI should look like etc. Currently I've added another tab to the GraphQL request pane to configure headers for the introspection query:

![image](https://github.com/usebruno/bruno/assets/3109364/c411ff1d-3067-4998-9210-247f136389ae)

**Comment by grubersjoe** [comment]
I've opened up a PR that adds the `Auth` tab to GraphQL requests to solve this.

**Comment by helloanoop** [comment]
Hey @grubersjoe 

Many Thanks!
I have merged the PR. There are still some enhancements that need to be implemented.
It'd be great if you could raise a new PR when you find some time.

The [prepare-gql-introspection-request.](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/prepare-gql-introspection-request.js) still uses mustache js which we no longer use.

We have started using handlebars at all [other places](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/interpolate-vars.js#L41-L60)

Changes needed
1. Update to use handlebars
2. Interpolate env variables

Bruno allows pulling dotenv varaibles at the root of you collection and accessing them via `{{process.env.secret}}`
See [docs](https://docs.usebruno.com/secrets-management/dotenv-file.html)

The current interpolation does not consider the interpolation of env vars.

**Comment by oscarpas** [comment]
This is a great addition. If you're still working on this @grubersjoe I have another use case that would be great if it's covered:

I need to set custom headers to authenticate the schema request. So either add a "custom header" option to the dropdown on the auth tab. Or use the headers from the headers tab when making the schema req.

Not sure what makes most sense. Looking at Postman they handle it like this, which also covers query params:

<img width="1242" alt="Skärmavbild 2023-10-06 kl  10 25 36" src="https://github.com/usebruno/bruno/assets/8113142/8823cd07-7465-4bf1-afee-ffb3017fc6e4">

**Comment by grubersjoe** [comment]
@oscarpas yes I plan to do the two things @helloanoop mentioned above.

About the headers: I already wondered if the set headers should also be used in the schema request. Your use case makes me think this would be a good idea 👍. I'm happy to add that as well in the PR.

**Comment by smitt04** [comment]
I would like to re-open this as apparently this only works if you set the header on the request, but not in an environment. I have an api key set in the environment headers and those don't seemed to get passed along

**Comment by Drowze** [comment]
I can also confirm this is still an issue. From my experience using basic authentication in a GraphQL API:
- on the Headers tab, specifying `Authorization` as something like `Basic dXNlcjpwYXNz`: **works fine in introspection requests**
- on the Auth tab, specifying `Basic Auth` username and password: **does not work in introspection requests**
- on the Script tab, specifying a simple script to add the basic authentication header: **does not work in introspection requests** (note: the script isn't even executed in introspection calls, e.g. `console.log` aren't written to console)

**Comment by kissgyorgy** [comment]
I have the same problem too, Auth tab doesn't work, setting the Authorization header manually on the Headers tab works even with variables.
