### ISSUE TITLE
Bug with sending request on VS code

### ISSUE THREAD

**Issue by fantastic0101** [usebruno/bruno#6378]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

2.15.1

### Operating System

Windows 10

### Describe the bug

Hi there.

I hope you are doing well.

I have encountered serious bug in using bruno extension with VS code.

If I try to send requst on VS code bruno extension, it shows this bug.

Please let me know how I can fix this problem.

Thank you.

### Screenshots/Live demo link

<img width="1496" height="771" alt="Image" src="https://github.com/user-attachments/assets/9fef191f-d4c3-409a-a82e-bb60bd312f4a" />

**Comment by stephanie-jourdan** [comment]
I have the same bug since this morning.... Tuesday, it was ok, with the same collection. I try to create new collections but the bug appear on every requests

**Comment by aletome** [comment]
Same here, after VS Code update to version 1.107.0.

**Comment by stephanie-jourdan** [comment]
I had to reinstall VS Code version 1.104.1 for it to work properly again.

**Comment by johngauto** [comment]
Might be seeing the same one, on v1.107.0 also (VSCode, fresh install on a Coder.com environment (Debian bookworm - 12.7, an up to date Google-Chrome browser).
Anytime I select the Script or Test tab for a collection folder (ie. click across from the default Headers tab selection), it crashes. Same whether in safe mode or developer mode.
A browser reload doesn't help. Will try disabling some other plugins and try again in case. Have a single global environment with nothing in it, and 3 environments for each collection (but they don't show up where I'd expect them to when I click). The script/test pages start to render when I click, for just a fraction of a moment, but are gone and replaced by the Oops page immediately. If I close that vscode tab and re-open a folder's settings from the 3-dot menu it comes back as the Header tab showing ok (empty, btw), but continues to fail when I select Script/Test every time.

Unsure if I can get 1.104 rolled back to here in a reasonable time to test it.

**Comment by NourElDin023** [comment]
> Same here, Fedora KDE Linux 43 VS Code v 1.107.0 Bruno v 4.4.0 The bug appeared after the last VS Code update

Updated to VS Code v 1.107.1 and the issue still persist

**Comment by naman-bruno** [comment]
Hi everyone, this issue is now resolved.
We’ve published the fix to both the VS Code Marketplace and Open VSX.
Update the extension to the latest version and let us know if everything looks good on your end.
Thanks for reports!

**Comment by jprusch** [comment]
@naman-bruno Could you check again? The extension is working now, so this elaborated the bug somehow, but I just wnated to let you know.

**Comment by naman-bruno** [comment]
Yes sure, I’ll check it again and see what might have caused this.

**Comment by Buronn** [comment]
I still have the issue. It happens randomly; if I click "Return to App" several times, it works (sometimes).
