### ISSUE TITLE
[FEATURE] Support Postman pre-request script and tests when Importing collection

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#710]
In postman, I have this in my request
![image](https://github.com/usebruno/bruno/assets/191879/3a8025bd-7c36-4c46-bc04-eaf2457b2f96)
![image](https://github.com/usebruno/bruno/assets/191879/fcfa1431-cf20-47d4-9da1-3dfe36bc7350)

In bruno I have this : 
![image](https://github.com/usebruno/bruno/assets/191879/fbfaef06-333e-4967-8603-ab2d54844db7)
![image](https://github.com/usebruno/bruno/assets/191879/5ae8989a-46a8-40e3-a4f0-596e7d1402b5)

the section in Postman collection
 `````json
{
							"name": "uploads an image",
							"event": [
								{
									"listen": "prerequest",
									"script": {
										"exec": [
											"ceci est un pre-script"
										],
										"type": "text/javascript"
									}
								},
								{
									"listen": "test",
									"script": {
										"exec": [
											"ceci est un test"
										],
										"type": "text/javascript"
									}
								}
							],
							"request": {
								"auth": {
									"type": "oauth2"
								},
								"method": "POST",
								"header": [
									{
										"key": "Content-Type",
										"value": "application/octet-stream"
									}
								],
								"body": {
									"mode": "raw",
									"raw": "{body in json}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{baseUrl}}/pet/:petId/uploadImage?additionalMetadata=Duis Lorem in nisi aliquip",
									"host": [
										"{{baseUrl}}"
									],
									"path": [
										"pet",
										":petId",
										"uploadImage"
									],
									"query": [
										{
											"key": "additionalMetadata",
											"value": "Duis Lorem in nisi aliquip",
											"description": "Additional Metadata"
										}
									],
									"variable": [
										{
											"key": "petId",
											"value": "15607064",
											"description": "(Required) ID of pet to update"
										}
									]
								}
							},
							"response": [
								{
									"name": "successful operation",
									"originalRequest": {
										"method": "POST",
										"header": [
											{
												"description": "Added as a part of security scheme: oauth2",
												"key": "Authorization",
												"value": "<token>"
											}
										],
										"body": {
											"mode": "file",
											"file": {}
										},
										"url": {
											"raw": "{{baseUrl}}/pet/:petId/uploadImage?additionalMetadata=Duis Lorem in nisi aliquip",
											"host": [
												"{{baseUrl}}"
											],
											"path": [
												"pet",
												":petId",
												"uploadImage"
											],
											"query": [
												{
													"key": "additionalMetadata",
													"value": "Duis Lorem in nisi aliquip"
												}
											],
											"variable": [
												{
													"key": "petId",
													"value": "15607064",
													"description": "(Required) ID of pet to update"
												}
											]
										}
									},
									"status": "OK",
									"code": 200,
									"_postman_previewlanguage": "json",
									"header": [
										{
											"key": "Content-Type",
											"value": "application/json"
										}
									],
									"cookie": [],
									"body": "{\n \"message\": \"Lorem est sit\",\n \"type\": \"amet veniam nisi dolor\",\n \"code\": -34649923\n}"
								}
							]
						}

````

Bruno should be able to parse the block "event"

**Comment by helloanoop** [comment]
Support has been delivered for this in `v0.27.0` by @survivant !

@survivant as discussed in the PR, when you find some time, please raise a new PR for having very line commented //. This allows the user to gradually migrate the tests and scripts, but also the app not to crash since pm variable is not found.

**Comment by survivant** [comment]
> Support has been delivered for this in `v0.27.0` by @survivant !
> 
> @survivant as discussed in the PR, when you find some time, please raise a new PR for having very line commented //. This allows the user to gradually migrate the tests and scripts, but also the app not to crash since pm variable is not found.

Done here : https://github.com/usebruno/bruno/pull/733

**Comment by eloo-abi** [comment]
@survivant not really
the change in https://github.com/usebruno/bruno/pull/733/files#diff-c41935360b7168d52318938cbf7104471d881344db8e642557537dff0f0d0c52 will only import the very first line of the script 

so if you have a multiline script, which is pretty common, you will only have the very first line

**Comment by survivant** [comment]
Please check the PR #753

Le mer. 25 oct. 2023, 08 h 05, Joseph Weigl ***@***.***> a
écrit :

**Comment by helloanoop** [comment]
@eloo-abi The latest release 0.27.2 should have the new updates

**Comment by eloo-abi** [comment]
@survivant @helloanoop 
i have tested this with 0.27.2 and it seems to not work.. 
i guess the problem is still the `[0]` in the `exec`
```
brunoRequestItem.request.script.req = event.script.exec[0]
```

here is an example of a collection we have

```
					"listen": "test",
					"script": {
						"exec": [
							"tests['Status 200'] = responseCode.code === 200;",
							"",
							"var validJSON = false;",
							"var resData = {};",
...
```
and we see here that each line is a single entry in the array

the postman schema of this collection is:
```
"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
```

**Comment by survivant** [comment]
Can you put the payload in this ticket and I will fix it. Sorry

Le mer. 25 oct. 2023, 10 h 31, Joseph Weigl ***@***.***> a
écrit :

**Comment by survivant** [comment]
with the latest fix.
![image](https://github.com/usebruno/bruno/assets/191879/da47397c-5765-487b-a9e3-a4625cb102fd)

**Comment by eloo-abi** [comment]
@survivant looks good :) 
will test it with the next release

thanks for the quick response and fix
