### ISSUE TITLE
[Bug] - URLEncode edited Query parameters from the dedicated table/tab on change

### ISSUE THREAD

**Issue by l0new4nder3r** [usebruno/bruno#732]
I imported requests a while ago now, and some were imported with query parameters like dates:

`?from=2023-10-23T00%3A00%3A00%2B00%3A00&to=2023-10-23T23%3A59%3A59%2B00%3A00`

They work fine when I run them.
The Query tab allows me to see what the current decoded values are (nice for human eyes! ❤️).
![image](https://github.com/usebruno/bruno/assets/27144372/1f32f66e-b487-40cd-a94f-52363d002c58)

But when I modify my "from" date, by example starting a day earlier, in the Value field of the Query tab, then the URL is immediately altered, and the query params are no longer encoded - making my request fail, and me losing the previously encoded value that was running fine before 😞 

`?from=2023-10-22T00:00:00+00:00&to=2023-10-23T23:59:59+00:00`

I can ctrl-z to get back to it, and manually fix it, but altering the encoded value itself in the main URL can sometimes be tedious.
And we are not far from having something a nice user experience here - my suggestion : when editing any value within the "Query" tab, automatically apply URLEncode while updating the resulting URL.

**Comment by l0new4nder3r** [comment]
@Its-treason 
Fair enough! 
I was unaware of such a possible use case.
As long as it is possible and easy to use, totally fine by me :)

Could it be some box to tick in the Query tab? 
One per line, would be weird though.
And having this option set globally would defeat the possibility to have URLEncode and not URLEncode in the same instance.

What do you think? @helloanoop any idea of what the design could be?

**Comment by Its-treason** [comment]
One checkbox per line is definitely too much, I was thinking about putting a checkbox under the right side of the table.

**Comment by CarlosLecval** [comment]
Hi, this is what I worked on

https://github.com/usebruno/bruno/assets/61945879/0a38a6e9-1a46-4487-90fb-60912fb28a35

**Comment by Darwin1337** [comment]
This issue is very frustrating and it would be nice to see it fixed!

**Comment by riekusr** [comment]
Also in need of this

**Comment by l0new4nder3r** [comment]
Temporary workaround using this "script > pre-request" line

`req.setUrl(req.getUrl().replace(/(.+?\?).+/,'$1') + encodeURIComponent(req.getUrl().replace(/.+?\?/,'')));`

**Comment by helloanoop** [comment]
After reviewing the related issues, I believe the root cause of many of them is an inconsistency in how Bruno handles URL encoding between the below two components
- URL Input Box
- Query Parameters Table

Currently, Bruno automatically decodes the URL from the input field using URLSearchParams. However, when changes are made in the query parameters table, those changes are not encoded before updating the URL in the input field. This inconsistency leads to confusion and creates a number of edge cases.

Another challenge is that we cannot determine whether the URL entered in the input field is already encoded. Given this uncertainty, it is not ideal for Bruno to assume the URL is encoded and then proceed with decoding while populating the query parameters table.

**Solution**
To resolve this, we are considering the following approach:
1. Bruno will not perform any encoding or decoding in the UI. The URL input field and the query parameters table will remain identical.
2. At the time of sending the request, Bruno will encode the query parameters using JavaScript's encodeURIComponent function. This will be the default behavior, but users will have the option to disable encoding via a setting if needed.

**Tradeoff:**
With the current implementation, when users input an encoded URL, Bruno decodes it before displaying it, making it easier to read. With the new approach, encoded URLs will remain as entered, which may reduce readability in some cases.
Ex: `?from=2023-10-23T00%3A00%3A00%2B00%3A00&to=2023-10-23T23%3A59%3A59%2B00%3A00`

**Comment by Kwaadpepper** [comment]
Could a checkbox be added nearby each query line to specify that a query should be url encoded ?

**Comment by helloanoop** [comment]
@Kwaadpepper As commented here https://github.com/usebruno/bruno/issues/732#issuecomment-1775923313 a checkbox per line seems too much

Do you have cases where you'd want to encode some params, but not others ?

**Comment by Kwaadpepper** [comment]
> @Kwaadpepper As commented here https://github.com/usebruno/bruno/issues/732#issuecomment-1775923313 a checkbox per line seems too much
> 
> Do you have cases where you'd want to encode some params, but not others ?

No but I figured that it would be easier that optin url encode any param since it actually doesn't url encode. That was triggering silent fail for my usage. It took me some time to figure out that Bruno does not url encode query params I was expecting it to do it by default.

I am sending simple strings along with more complex ones. I liked the fact that I would put them non encoded and therefore readable in the table. I have no benefit seeing the encoded one. For now copy paste encoded strings for thoses that would break the query.

For example I am sending user agent string on query and I did not understand why on the serveur I was getting incorrect information. It could be helpful to see the real request that was made.

**Comment by UnleashSpirit** [comment]
Hi, I just have this issue to for some RSQL API.
Perhaps one option would be to do it like Postman does with a right-click ?
It's much less user-friendly and automatic than a checkbox, but it may cover the encoding of certain parameters.

![Image](https://github.com/user-attachments/assets/ff86fb50-70f3-4acb-9bd5-67d516cae059)

I'd also like to have a single checkbox, but it would require a tooltip or something similar to immediately see the difference between "encode" and "send." However, I don't really see the point of it, so a global checkbox, like in the video, would be fine for me.

**Comment by joaoduarte19** [comment]
Any news on the resolution of this issue?

**Comment by anusree-bruno** [comment]
@joaoduarte19 We need some time to investigate a proper solution for this. I will be able to give you some update in 2 weeks.

**Comment by nedy13** [comment]
This issue causes a lot of trouble until we recognized that Bruno is not encoding the parameters on its own. We though there is an implementation issue in our service.

This bug exists since two years and is impacting the daily work of a lot of people.

My user perspective is: if you copy a url string to the line, then Bruno should consume as it is. The values should still be encoded. If they are not encoded, then they should be used as is.

Example:
`{{base_url}}/api/records/query?&eds=EDS%233456`

is encoded and the table below should show
eds | EDS#3456

If you typ this in the table: EDS%233456, then the resulting url should be: `{{base_url}}/api/records/query?&eds=EDS%25233456`

This would be my user expectation.

**Comment by Kwaadpepper** [comment]
> This issue causes a lot of trouble until we recognized that Bruno is not encoding the parameters on its own. We though there is an implementation issue in our service.
> 
> This bug exists since two years and is impacting the daily work of a lot of people.
> 
> My user perspective is: if you copy a url string to the line, then Bruno should consume as it is. The values should still be encoded. If they are not encoded, then they should be used as is.
> 
> Example: `{{base_url}}/api/records/query?&eds=EDS%233456`
> 
> is encoded and the table below should show eds | EDS#3456
> 
> If you typ this in the table: EDS%233456, then the resulting url should be: `{{base_url}}/api/records/query?&eds=EDS%25233456`
> 
> This would be my user expectation.

Then the behavior would be like a regular web browser. This make sense but I would like that Bruno does the url encoding job if I ask him to do so.
This is because the original query parameter is human readable.
For any one to open the Bruno, they should read the request version for humans.

**Comment by maintainer-bruno** [comment]
This issue has been resolved by #5089 and is available starting from v2.8.0.

URL encoding is no longer visibly applied in the UI — both the Params table and the Request URL field now display values exactly as entered by the user. Bruno will continue to send encoded values to the API server (unless URL encoding is explicitly disabled in the Settings tab for each request).

> 🔧 Note:
> URL encoding is enabled by default for newly created requests. However, for backward compatibility, requests from older collections will require manual enabling of this setting if needed.

Closing this issue now. Feel free to reopen it if you continue to experience the problem.

**Comment by UnleashSpirit** [comment]
For those looking for how to manually enable this option, it's a per request's setting.
Settings tab > URL Encoding.

<img width="423" height="278" alt="Image" src="https://github.com/user-attachments/assets/b483ba8d-8440-4817-8530-ba588275a6eb" />

Or in the .bru file
```javascript
settings {
  encodeUrl: true
}
```

**Comment by jmarcher** [comment]
> For those looking for how to manually enable this option, it's a per request's setting. Settings tab > URL Encoding.
> <img alt="Image" width="423" height="278" src="https://private-user-images.githubusercontent.com/6216968/474882186-b483ba8d-8440-4817-8530-ba588275a6eb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcyMjYwMjAsIm5iZiI6MTc4NzIyNTcyMCwicGF0aCI6Ii82MjE2OTY4LzQ3NDg4MjE4Ni1iNDgzYmE4ZC04NDQwLTQ4MTctODUzMC1iYTU4ODI3NWE2ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MjBUMTEzNTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNmMGFiZTk2NmYyNmYyODQ3OWI3N2RjZDBhN2RiMjUyZjFjOWZhZWExODQwOTIxYjk4ZjJmZTEwOTRhMzY4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.ogooFAtTnUTUkY1RFSRwgdEmDXxzh566lKRW5w4JnuQ">
> 
> Or in the .bru file
> 
> settings {
>   encodeUrl: true
> }

This does not work

When sending this: 

<img width="996" height="342" alt="Image" src="https://github.com/user-attachments/assets/8c4fbf56-44e6-4070-8a56-8bed08c48a8f" />

It generates a new parameter &musik .... 

Postman does it correctly

**Comment by jmarcher** [comment]
I can confirm this issue still happens when the query parameters are sent in a POST or PATCH call, GET Call gets encoded just fine

**Comment by jmarcher** [comment]
@maintainer-bruno
