### ISSUE TITLE
[Bug] whitescreen when starting bruno

### ISSUE THREAD

**Issue by BranKohlschreiber** [usebruno/bruno#777]
I use Ubuntu 22.04.3 LTS to install bruno via snap as recommended by the documentation 

`snap install bruno`

it installs version 0.27.2
![image](https://github.com/usebruno/bruno/assets/62992330/975601bb-0434-4545-9c33-1db75b09dde9)

when starting bruno i get a white screen
![image](https://github.com/usebruno/bruno/assets/62992330/31a43268-eda5-4348-8376-dcc242a8d045)

and the following error log:

> Preferences file is located at: /home/bran/snap/bruno/7/.config/bruno/preferences.json
>
>(bruno:17091): Gtk-WARNING **: 09:57:07.119: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property >name
>
>(bruno:17091): Gtk-WARNING **: 09:57:07.122: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property >name
>
>(bruno:17091): Gtk-WARNING **: 09:57:07.123: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property >name
>(node:17091) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
>   at exports.setContentSecurityPolicy (/snap/bruno/7/resources/app.asar/node_modules/electron-util/index.js:150:9)
>(Use `bruno --trace-warnings ...` to show where the warning was created)
>(node:17091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an >async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on >unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>(node:17091) electron: Failed to load URL: file:///snap/bruno/7/resources/app.asar/web/index.html with error: ERR_FILE_NOT_FOUND
>[17091:1025/095707.270425:ERROR:interface_endpoint_client.cc(689)] Message 0 rejected by interface blink.mojom.WidgetHost

**Comment by ThomasEcherer** [comment]
i have the same, or similar problem.
I have the same version 0.27.2 from snap, and the app behavior is a whitescreen.

The log says a little bit different:

```
Preferences file is located at: /root/snap/bruno/7/.config/bruno/preferences.json
Gtk-Message: 13:39:32.158: Failed to load module "pk-gtk-module"
Gtk-Message: 13:39:32.163: Failed to load module "pk-gtk-module"
[81814:1026/133932.174490:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[81814:1026/133932.174520:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[81814:1026/133932.209512:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
(node:81814) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
    at exports.setContentSecurityPolicy (/snap/bruno/7/resources/app.asar/node_modules/electron-util/index.js:150:9)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:81814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
/usr/share/libdrm/amdgpu.ids: No such file or directory
(node:81814) electron: Failed to load URL: file:///snap/bruno/7/resources/app.asar/web/index.html with error: ERR_FILE_NOT_FOUND

```

**Comment by BranKohlschreiber** [comment]
file:///snap/bruno/7/resources/app.asar/web/index.html

does not exist on my system. app.asar is a json file and not a directory

installing it via debian package did also not work although that might be due to some probably unrelated problems on my side.

**Comment by helloanoop** [comment]
@niqdev @BranKohlschreiber @ThomasEcherer 

I have fixed this in a new snap release 0.27.3
Can you please check now ?

**Comment by ThomasEcherer** [comment]
i've updated bruno
```
name:      bruno
summary:   Bruno
publisher: Anoop M D (helloanoop)
store-url: https://snapcraft.io/bruno
contact:   anoop.md1421@gmail.com
license:   unset
description: |
  Opensource API Client for Exploring and Testing APIs
commands:
  - bruno
snap-id:      TjcIukBMos0pUSGGmsN4sx2rcnp4B8I3
tracking:     latest/stable
refresh-date: today at 16:52 CEST
channels:
  latest/stable:    0.27.2 2023-10-27 (8) 85MB -
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      ↑                          
installed:          0.27.2            (8) 85MB -
```
it still says `0.27.2` and not `0.27.3`. But the version-date has changed to 2023-10-27 and it is not 8 instead of 7.

when i try to start bruno i have no withescreen anymore but it still throws an error:
```
Preferences file is located at: /root/snap/bruno/8/.config/bruno/preferences.json
Gtk-Message: 16:54:31.757: Failed to load module "pk-gtk-module"
Gtk-Message: 16:54:31.758: Failed to load module "pk-gtk-module"
[149459:1027/165431.769981:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[149459:1027/165431.770004:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
/usr/share/libdrm/amdgpu.ids: No such file or directory
[149459:1027/165431.805953:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
(node:149459) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
    at exports.setContentSecurityPolicy (/snap/bruno/8/resources/app.asar/node_modules/electron-util/index.js:150:9)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:149459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Comment by niqdev** [comment]
yup, works for me now too, thanks!

**Comment by BranKohlschreiber** [comment]
can confirm too. Thanks for the quick fix!

**Comment by helloanoop** [comment]
@ThomasEcherer Perhaps there was a delay in snap build getting published. 

Since @niqdev and @BranKohlschreiber confirmed that it works on their machines, Can you attempt it again ?

**Comment by ThomasEcherer** [comment]
@helloanoop i do not get it working.

my steps:
- remove bruno package
- refresh snap
- install bruno again

at first the app looks fine, but then the erros appear and the app breaks
```
(node:20562) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
    at exports.setContentSecurityPolicy (/snap/bruno/8/resources/app.asar/node_modules/electron-util/index.js:150:9)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:20562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

you said in your update the version should be 0.27.**3** ? but if i install bruno it still says 0.27.**2**.
When i look at https://snapcraft.io/bruno it also says 0.27.**2** ?

**Comment by sanjai0py** [comment]
Closing this as stale. The issue seems to be solved in the latest versions of Bruno. Please open a new issue if the problem persists.
